spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 8080

livekit:
  url: wss://debbly.duckdns.org
  api-key:
  api-secret: