package com.debbly.server.auth

enum class AuthErrorCode {
    AUTH_INVALID_USERNAME,
    AUTH_INVALID_BIRTHDATE,
    AUTH_EMAIL_ALREADY_REGISTERED,
    AUTH_EMAIL_REGISTERED_UNCONFIRMED,
    AUTH_CONFIRMATION_CODE_INVALID,
    AUTH_LOGIN_FAILED,
    LOGOUT_FAILED,
    RESET_PASSWORD_FAILED,
    FORGOT_PASSWORD_FAILED,
    RESEND_CONFIRMATION_FAILED,
    AUTH_USER_INCOMPLETE,
    AUTH_TOO_MANY_ATTEMPTS,
    AUTH_GENERIC_ERROR
}