package com.debbly.server.auth

enum class AuthErrorCode {
    AUTH_INVALID_USERNAME,
    AUTH_INVALID_BIRTHDATE,
    AUTH_EMAIL_ALREADY_REGISTERED,
    AUTH_EMAIL_REGISTERED_UNCONFIRMED,
    AUTH_CONFIRMATION_CODE_INVALID,
    AUTH_LOGIN_FAILED,
    AUTH_LOGOUT_FAILED,
    AUTH_RESET_PASSWORD_FAILED,
    AUTH_FORGOT_PASSWORD_FAILED,
    AUTH_RESEND_CONFIRMATION_FAILED,
    AUTH_USER_INCOMPLETE,
    AUTH_TOO_MANY_ATTEMPTS,
    AUTH_REFRESH_TOKEN_INVALID,
    AUTH_CALLBACK_INVALID_TOKEN,
    AUTH_CALLBACK_TOKEN_VALIDATION_FAILED,
    AUTH_CALLBACK_USER_CREATION_FAILED,
    AUTH_GENERIC_ERROR
}