redis:
  address: localhost:6379

api_key: APIQEFqAeLvpLmr
api_secret: nDL858eoOvpcfuaonOfHcVXzo9hJkD4efk76sOBTqVfD
ws_url: ws://localhost:7880

s3:
  access_key: AKIARU3CPQWX2VQ33VZA
  secret: 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
  region: us-west-2
  bucket: debbly-livekit-egress

